apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: pyspark-k8s
  namespace: spark 
spec:
  type: Python
  mode: cluster
  image: "carlosbpy/spark-py:latest"
  imagePullPolicy: Always
  mainApplicationFile: local:///app/spark.py
  sparkVersion: "3.1.2"
  restartPolicy:
    type: Never
  volumes:
    - name: "shared-volume"
      hostPath:
        path: "/tmp"
        type: Directory
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.1.2
    serviceAccount: spark
    volumeMounts:
      - name: "shared-volume"
        mountPath: "/tmp"
  executor:
    cores: 1
    instances: 1
    memory: "1024m"
    labels:
      version: 3.1.2
    volumeMounts:
      - name: "shared-volume"
        mountPath: "/tmp"